// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	CgroupId    uint64
	Retval      int64
	DurationNs  uint64
	Pid         uint32
	Tid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	EventType   uint32
	Fd          int32
	Flags       uint32
	Family      uint16
	Port        uint16
	AddressV4   uint32
	AddressV6   [16]uint8
	Argc        uint32
	Comm        [16]int8
	ParentComm  [16]int8
	Path        [256]int8
	Argv        [6][128]int8
	_           [4]byte
}

type bpfProbeStats struct {
	_                     structs.HostLayout
	EventsEmitted         uint64
	RingbufOutputFailures uint64
	PendingUpdateFailures uint64
	PendingLookupMisses   uint64
	PendingTypeMismatches uint64
	PendingDeleteFailures uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents                 = "events"
	bpfMapPendingEvents          = "pending_events"
	bpfMapProbeStats             = "probe_stats"
	bpfMapScratchEvents          = "scratch_events"
	bpfProgTraceConnectEnter     = "trace_connect_enter"
	bpfProgTraceConnectExit      = "trace_connect_exit"
	bpfProgTraceExecveEnter      = "trace_execve_enter"
	bpfProgTraceExecveExit       = "trace_execve_exit"
	bpfProgTraceOpenatEnter      = "trace_openat_enter"
	bpfProgTraceOpenatExit       = "trace_openat_exit"
	bpfProgTraceSchedProcessFork = "trace_sched_process_fork"
	bpfProgTraceSetuidEnter      = "trace_setuid_enter"
	bpfProgTraceSetuidExit       = "trace_setuid_exit"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceConnectEnter     *ebpf.ProgramSpec `ebpf:"trace_connect_enter"`
	TraceConnectExit      *ebpf.ProgramSpec `ebpf:"trace_connect_exit"`
	TraceExecveEnter      *ebpf.ProgramSpec `ebpf:"trace_execve_enter"`
	TraceExecveExit       *ebpf.ProgramSpec `ebpf:"trace_execve_exit"`
	TraceOpenatEnter      *ebpf.ProgramSpec `ebpf:"trace_openat_enter"`
	TraceOpenatExit       *ebpf.ProgramSpec `ebpf:"trace_openat_exit"`
	TraceSchedProcessFork *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSetuidEnter      *ebpf.ProgramSpec `ebpf:"trace_setuid_enter"`
	TraceSetuidExit       *ebpf.ProgramSpec `ebpf:"trace_setuid_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	PendingEvents *ebpf.MapSpec `ebpf:"pending_events"`
	ProbeStats    *ebpf.MapSpec `ebpf:"probe_stats"`
	ScratchEvents *ebpf.MapSpec `ebpf:"scratch_events"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	PendingEvents *ebpf.Map `ebpf:"pending_events"`
	ProbeStats    *ebpf.Map `ebpf:"probe_stats"`
	ScratchEvents *ebpf.Map `ebpf:"scratch_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.PendingEvents,
		m.ProbeStats,
		m.ScratchEvents,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceConnectEnter     *ebpf.Program `ebpf:"trace_connect_enter"`
	TraceConnectExit      *ebpf.Program `ebpf:"trace_connect_exit"`
	TraceExecveEnter      *ebpf.Program `ebpf:"trace_execve_enter"`
	TraceExecveExit       *ebpf.Program `ebpf:"trace_execve_exit"`
	TraceOpenatEnter      *ebpf.Program `ebpf:"trace_openat_enter"`
	TraceOpenatExit       *ebpf.Program `ebpf:"trace_openat_exit"`
	TraceSchedProcessFork *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSetuidEnter      *ebpf.Program `ebpf:"trace_setuid_enter"`
	TraceSetuidExit       *ebpf.Program `ebpf:"trace_setuid_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceConnectEnter,
		p.TraceConnectExit,
		p.TraceExecveEnter,
		p.TraceExecveExit,
		p.TraceOpenatEnter,
		p.TraceOpenatExit,
		p.TraceSchedProcessFork,
		p.TraceSetuidEnter,
		p.TraceSetuidExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
