apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daemonset.yaml
  - networkpolicy.yaml
  - service.yaml
images:
  - name: kernel-sentinel
    newName: ghcr.io/vincent-p-essy/kernel-sentinel
    newTag: 0.1.0
